name: stem_bosque
description: "DSL para programación de robots - StemBosque IDE"
publish_to: 'none'

version: 0.5.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Gestión de archivos (solo lo esencial)
  file_picker: ^8.1.4
  path_provider: ^2.1.5

  # Bluetooth BLE
  flutter_blue_plus: 1.32.12
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true 